name: PR to main

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main


jobs:
  test_package:
    name: Test package build
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build the package
        run: python -m build


  test_website:
    name: Test website build
    runs-on: ubuntu-latest

    steps:
      - name: Checking out source repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          cd ${{ github.workspace }}/website/reasonchip/
          python -m pip install --upgrade pip
          pip install -r ./requirements.txt

      - name: Install reasonchip
        run: |
          cd ${{ github.workspace }}/
          pip install -e .          

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'

      - name: Build chipset documentation
        run: |
          cd ${{ github.workspace }}/website/reasonchip/
          ./rebuild.sh

      - name: Build website
        run: |
          cd ${{ github.workspace }}/website/reasonchip/
          hugo --minify

